version: "3.8"

services:
  meditationapp:
    build: .
    container_name: meditation_app
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./:/app 
    command: ["dotnet", "watch", "run"]
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: meditation_db
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: "1433"
      MSSQL_PID: "Developer"
    volumes:
    - ./mssql-data:/var/opt/mssql